<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RandomBot.Domain\RandomBot.Domain.csproj" />
    <ProjectReference Include="..\RandomBot.Infrastructure\RandomBot.Infrastructure.csproj" />
    <ProjectReference Include="..\RandomBot.Application\RandomBot.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
