name: Randombot quick checks

on:
  push:
    paths:
      - "api/**"
  pull_request:
    paths:
      - "api/**"

jobs:
  api:
    runs-on: ubuntu-latest

    services:
      mmariadb:
        image: mariadb:11.4
        env:
          MARIADB_ROOT_PASSWORD: testpass
          MARIADB_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -ptestpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Run Prettier
        working-directory: ./api
        run: npm run format

      - name: Run ESLint
        working-directory: ./api
        run: npm run lint

      - name: Run tests
        working-directory: ./api
        env:
          NODE_ENV: test
          TEST_DB_NAME: test_db
          DB_ADMIN_USERNAME: root
          DB_ADMIN_PASSWORD: testpass
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DIALECT: mariadb
        run: npm test
